"""Update model Taks. Fix created_at

Revision ID: 775a6fa3c890
Revises: 5661b7b03fbd
Create Date: 2025-07-29 22:07:44.756493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775a6fa3c890'
down_revision: Union[str, Sequence[str], None] = '5661b7b03fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
