"""Update model Taks. Fix created_at 2

Revision ID: a98dd48e8a48
Revises: 775a6fa3c890
Create Date: 2025-07-29 22:12:00.067973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98dd48e8a48'
down_revision: Union[str, Sequence[str], None] = '775a6fa3c890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
