"""Update model Taks. Fix created_at add timezone Kemerovo

Revision ID: 2293c49b7cee
Revises: a98dd48e8a48
Create Date: 2025-07-29 22:21:50.983051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2293c49b7cee'
down_revision: Union[str, Sequence[str], None] = 'a98dd48e8a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
